services:
  - type: web
    name: power-supply-feedback
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Power Supply Feedback
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
